USE [QuanLy_HieuSuat];
GO

SET NOCOUNT ON;
GO

BEGIN TRY
    BEGIN TRAN;

    /*
        Seed du lieu mau phuc vu test he thong, dac biet la AI.
        - KHONG xoa du lieu hien co.
        - KHONG sua/xoa NHANVIEN MANHANVIEN = 1 (Admin).
        - KHONG sua/xoa bang TRANGTHAICONGVIEC.
        Script co the chay lap lai an toan (idempotent theo ten/email mau).
    */

    DECLARE @Now DATETIME = GETDATE();

    -- 1) Lay ma trang thai theo ten (fallback theo ID pho bien)
    DECLARE @TT_ChuaBatDau INT = (
        SELECT TOP 1 MATRANGTHAI FROM TRANGTHAICONGVIEC WHERE TENTRANGTHAI = N'Chưa bắt đầu'
    );
    DECLARE @TT_DangLam INT = (
        SELECT TOP 1 MATRANGTHAI FROM TRANGTHAICONGVIEC WHERE TENTRANGTHAI = N'Đang thực hiện'
    );
    DECLARE @TT_HoanThanh INT = (
        SELECT TOP 1 MATRANGTHAI FROM TRANGTHAICONGVIEC WHERE TENTRANGTHAI = N'Hoàn thành'
    );
    DECLARE @TT_ChoDuyet INT = (
        SELECT TOP 1 MATRANGTHAI FROM TRANGTHAICONGVIEC WHERE TENTRANGTHAI = N'Chờ duyệt'
    );

    SET @TT_ChuaBatDau = ISNULL(@TT_ChuaBatDau, 1);
    SET @TT_DangLam = ISNULL(@TT_DangLam, 2);
    SET @TT_HoanThanh = ISNULL(@TT_HoanThanh, 3);
    SET @TT_ChoDuyet = ISNULL(@TT_ChoDuyet, 4);

    -- 2) Phong ban mau
    IF NOT EXISTS (SELECT 1 FROM PHONGBAN WHERE TENPHONGBAN = N'MauAI-Phong Ky Thuat')
        INSERT INTO PHONGBAN (TENPHONGBAN, MOTA, MATRUONGPHONG)
        VALUES (N'MauAI-Phong Ky Thuat', N'Phong mau cho test AI va phan cong', NULL);

    IF NOT EXISTS (SELECT 1 FROM PHONGBAN WHERE TENPHONGBAN = N'MauAI-Phong San Pham')
        INSERT INTO PHONGBAN (TENPHONGBAN, MOTA, MATRUONGPHONG)
        VALUES (N'MauAI-Phong San Pham', N'Phong mau cho test KPI va du an', NULL);

    IF NOT EXISTS (SELECT 1 FROM PHONGBAN WHERE TENPHONGBAN = N'MauAI-Phong Van Hanh')
        INSERT INTO PHONGBAN (TENPHONGBAN, MOTA, MATRUONGPHONG)
        VALUES (N'MauAI-Phong Van Hanh', N'Phong mau cho test tien do/tre han', NULL);

    DECLARE @PB_KT INT = (SELECT TOP 1 MAPHONGBAN FROM PHONGBAN WHERE TENPHONGBAN = N'MauAI-Phong Ky Thuat');
    DECLARE @PB_SP INT = (SELECT TOP 1 MAPHONGBAN FROM PHONGBAN WHERE TENPHONGBAN = N'MauAI-Phong San Pham');
    DECLARE @PB_VH INT = (SELECT TOP 1 MAPHONGBAN FROM PHONGBAN WHERE TENPHONGBAN = N'MauAI-Phong Van Hanh');

    -- 3) Nhan vien mau (khong dong vao nhan vien #1)
    IF NOT EXISTS (SELECT 1 FROM NHANVIEN WHERE EMAIL = 'mau.tp.kt@demo.local')
        INSERT INTO NHANVIEN (MAPHONGBAN, HOTEN, NGAYSINH, CCCD, DIACHI, GIOITINH, EMAIL, SDT, NGAYVAOLAM, TRANGTHAI, SONAMKINHNGHIEM, DIEMKPI_TICHLUY)
        VALUES (@PB_KT, N'Mau Truong Phong Ky Thuat', '1988-04-12', '100000000101', N'Ha Noi', N'Nam', 'mau.tp.kt@demo.local', '0900000101', '2015-03-01', 1, 10, 88);

    IF NOT EXISTS (SELECT 1 FROM NHANVIEN WHERE EMAIL = 'mau.tp.sp@demo.local')
        INSERT INTO NHANVIEN (MAPHONGBAN, HOTEN, NGAYSINH, CCCD, DIACHI, GIOITINH, EMAIL, SDT, NGAYVAOLAM, TRANGTHAI, SONAMKINHNGHIEM, DIEMKPI_TICHLUY)
        VALUES (@PB_SP, N'Mau Truong Phong San Pham', '1990-02-10', '100000000102', N'Da Nang', N'Nu', 'mau.tp.sp@demo.local', '0900000102', '2017-01-15', 1, 8, 84);

    IF NOT EXISTS (SELECT 1 FROM NHANVIEN WHERE EMAIL = 'mau.tn.backend@demo.local')
        INSERT INTO NHANVIEN (MAPHONGBAN, HOTEN, NGAYSINH, CCCD, DIACHI, GIOITINH, EMAIL, SDT, NGAYVAOLAM, TRANGTHAI, SONAMKINHNGHIEM, DIEMKPI_TICHLUY)
        VALUES (@PB_KT, N'Mau Truong Nhom Backend', '1992-11-05', '100000000103', N'Ha Noi', N'Nam', 'mau.tn.backend@demo.local', '0900000103', '2018-06-10', 1, 7, 80);

    IF NOT EXISTS (SELECT 1 FROM NHANVIEN WHERE EMAIL = 'mau.tn.mobile@demo.local')
        INSERT INTO NHANVIEN (MAPHONGBAN, HOTEN, NGAYSINH, CCCD, DIACHI, GIOITINH, EMAIL, SDT, NGAYVAOLAM, TRANGTHAI, SONAMKINHNGHIEM, DIEMKPI_TICHLUY)
        VALUES (@PB_KT, N'Mau Truong Nhom Mobile', '1993-07-22', '100000000104', N'HCM', N'Nu', 'mau.tn.mobile@demo.local', '0900000104', '2019-04-18', 1, 6, 78);

    IF NOT EXISTS (SELECT 1 FROM NHANVIEN WHERE EMAIL = 'mau.nv.01@demo.local')
        INSERT INTO NHANVIEN (MAPHONGBAN, HOTEN, NGAYSINH, CCCD, DIACHI, GIOITINH, EMAIL, SDT, NGAYVAOLAM, TRANGTHAI, SONAMKINHNGHIEM, DIEMKPI_TICHLUY)
        VALUES (@PB_KT, N'Mau Nhan Vien 01', '1996-01-12', '100000000105', N'Ha Noi', N'Nam', 'mau.nv.01@demo.local', '0900000105', '2021-02-01', 1, 4, 74);

    IF NOT EXISTS (SELECT 1 FROM NHANVIEN WHERE EMAIL = 'mau.nv.02@demo.local')
        INSERT INTO NHANVIEN (MAPHONGBAN, HOTEN, NGAYSINH, CCCD, DIACHI, GIOITINH, EMAIL, SDT, NGAYVAOLAM, TRANGTHAI, SONAMKINHNGHIEM, DIEMKPI_TICHLUY)
        VALUES (@PB_SP, N'Mau Nhan Vien 02', '1997-03-07', '100000000106', N'Da Nang', N'Nu', 'mau.nv.02@demo.local', '0900000106', '2022-05-01', 1, 3, 69);

    IF NOT EXISTS (SELECT 1 FROM NHANVIEN WHERE EMAIL = 'mau.nv.03@demo.local')
        INSERT INTO NHANVIEN (MAPHONGBAN, HOTEN, NGAYSINH, CCCD, DIACHI, GIOITINH, EMAIL, SDT, NGAYVAOLAM, TRANGTHAI, SONAMKINHNGHIEM, DIEMKPI_TICHLUY)
        VALUES (@PB_SP, N'Mau Nhan Vien 03', '1995-08-19', '100000000107', N'HCM', N'Nam', 'mau.nv.03@demo.local', '0900000107', '2020-09-01', 1, 5, 72);

    IF NOT EXISTS (SELECT 1 FROM NHANVIEN WHERE EMAIL = 'mau.nv.04@demo.local')
        INSERT INTO NHANVIEN (MAPHONGBAN, HOTEN, NGAYSINH, CCCD, DIACHI, GIOITINH, EMAIL, SDT, NGAYVAOLAM, TRANGTHAI, SONAMKINHNGHIEM, DIEMKPI_TICHLUY)
        VALUES (@PB_VH, N'Mau Nhan Vien 04', '1994-09-29', '100000000108', N'Can Tho', N'Nu', 'mau.nv.04@demo.local', '0900000108', '2019-11-01', 1, 6, 58);

    IF NOT EXISTS (SELECT 1 FROM NHANVIEN WHERE EMAIL = 'mau.nv.05@demo.local')
        INSERT INTO NHANVIEN (MAPHONGBAN, HOTEN, NGAYSINH, CCCD, DIACHI, GIOITINH, EMAIL, SDT, NGAYVAOLAM, TRANGTHAI, SONAMKINHNGHIEM, DIEMKPI_TICHLUY)
        VALUES (@PB_VH, N'Mau Nhan Vien 05', '1998-12-02', '100000000109', N'Ha Noi', N'Nam', 'mau.nv.05@demo.local', '0900000109', '2023-01-10', 1, 2, 52);

    IF NOT EXISTS (SELECT 1 FROM NHANVIEN WHERE EMAIL = 'mau.nv.06@demo.local')
        INSERT INTO NHANVIEN (MAPHONGBAN, HOTEN, NGAYSINH, CCCD, DIACHI, GIOITINH, EMAIL, SDT, NGAYVAOLAM, TRANGTHAI, SONAMKINHNGHIEM, DIEMKPI_TICHLUY)
        VALUES (@PB_VH, N'Mau Nhan Vien 06', '1999-06-11', '100000000110', N'Da Nang', N'Nu', 'mau.nv.06@demo.local', '0900000110', '2023-07-01', 1, 1, 49);

    -- map id nhan vien mau
    DECLARE @NV_TPKT INT = (SELECT TOP 1 MANHANVIEN FROM NHANVIEN WHERE EMAIL = 'mau.tp.kt@demo.local');
    DECLARE @NV_TPSP INT = (SELECT TOP 1 MANHANVIEN FROM NHANVIEN WHERE EMAIL = 'mau.tp.sp@demo.local');
    DECLARE @NV_TNBE INT = (SELECT TOP 1 MANHANVIEN FROM NHANVIEN WHERE EMAIL = 'mau.tn.backend@demo.local');
    DECLARE @NV_TNMO INT = (SELECT TOP 1 MANHANVIEN FROM NHANVIEN WHERE EMAIL = 'mau.tn.mobile@demo.local');
    DECLARE @NV01 INT = (SELECT TOP 1 MANHANVIEN FROM NHANVIEN WHERE EMAIL = 'mau.nv.01@demo.local');
    DECLARE @NV02 INT = (SELECT TOP 1 MANHANVIEN FROM NHANVIEN WHERE EMAIL = 'mau.nv.02@demo.local');
    DECLARE @NV03 INT = (SELECT TOP 1 MANHANVIEN FROM NHANVIEN WHERE EMAIL = 'mau.nv.03@demo.local');
    DECLARE @NV04 INT = (SELECT TOP 1 MANHANVIEN FROM NHANVIEN WHERE EMAIL = 'mau.nv.04@demo.local');
    DECLARE @NV05 INT = (SELECT TOP 1 MANHANVIEN FROM NHANVIEN WHERE EMAIL = 'mau.nv.05@demo.local');
    DECLARE @NV06 INT = (SELECT TOP 1 MANHANVIEN FROM NHANVIEN WHERE EMAIL = 'mau.nv.06@demo.local');

    -- cap nhat truong phong
    UPDATE PHONGBAN SET MATRUONGPHONG = @NV_TPKT WHERE MAPHONGBAN = @PB_KT AND ISNULL(MATRUONGPHONG, 0) <> ISNULL(@NV_TPKT, 0);
    UPDATE PHONGBAN SET MATRUONGPHONG = @NV_TPSP WHERE MAPHONGBAN = @PB_SP AND ISNULL(MATRUONGPHONG, 0) <> ISNULL(@NV_TPSP, 0);

    -- 4) Nhom mau
    IF NOT EXISTS (SELECT 1 FROM NHOM WHERE TENNHOM = N'MauAI-Nhom Backend')
        INSERT INTO NHOM (TENNHOM, NGAYTAO) VALUES (N'MauAI-Nhom Backend', DATEADD(DAY, -200, @Now));

    IF NOT EXISTS (SELECT 1 FROM NHOM WHERE TENNHOM = N'MauAI-Nhom Mobile')
        INSERT INTO NHOM (TENNHOM, NGAYTAO) VALUES (N'MauAI-Nhom Mobile', DATEADD(DAY, -180, @Now));

    IF NOT EXISTS (SELECT 1 FROM NHOM WHERE TENNHOM = N'MauAI-Nhom QA')
        INSERT INTO NHOM (TENNHOM, NGAYTAO) VALUES (N'MauAI-Nhom QA', DATEADD(DAY, -120, @Now));

    DECLARE @NH_BACKEND INT = (SELECT TOP 1 MANHOM FROM NHOM WHERE TENNHOM = N'MauAI-Nhom Backend');
    DECLARE @NH_MOBILE INT = (SELECT TOP 1 MANHOM FROM NHOM WHERE TENNHOM = N'MauAI-Nhom Mobile');
    DECLARE @NH_QA INT = (SELECT TOP 1 MANHOM FROM NHOM WHERE TENNHOM = N'MauAI-Nhom QA');

    IF NOT EXISTS (SELECT 1 FROM THANHVIENNHOM WHERE MANHOM = @NH_BACKEND AND MANHANVIEN = @NV_TNBE)
        INSERT INTO THANHVIENNHOM (MANHOM, MANHANVIEN, NGAYGIANHAP, VAITROTRONGNHOM)
        VALUES (@NH_BACKEND, @NV_TNBE, DATEADD(DAY, -180, @Now), N'TruongNhom');

    IF NOT EXISTS (SELECT 1 FROM THANHVIENNHOM WHERE MANHOM = @NH_BACKEND AND MANHANVIEN = @NV01)
        INSERT INTO THANHVIENNHOM (MANHOM, MANHANVIEN, NGAYGIANHAP, VAITROTRONGNHOM)
        VALUES (@NH_BACKEND, @NV01, DATEADD(DAY, -170, @Now), N'ThanhVien');

    IF NOT EXISTS (SELECT 1 FROM THANHVIENNHOM WHERE MANHOM = @NH_MOBILE AND MANHANVIEN = @NV_TNMO)
        INSERT INTO THANHVIENNHOM (MANHOM, MANHANVIEN, NGAYGIANHAP, VAITROTRONGNHOM)
        VALUES (@NH_MOBILE, @NV_TNMO, DATEADD(DAY, -160, @Now), N'TruongNhom');

    IF NOT EXISTS (SELECT 1 FROM THANHVIENNHOM WHERE MANHOM = @NH_MOBILE AND MANHANVIEN = @NV02)
        INSERT INTO THANHVIENNHOM (MANHOM, MANHANVIEN, NGAYGIANHAP, VAITROTRONGNHOM)
        VALUES (@NH_MOBILE, @NV02, DATEADD(DAY, -150, @Now), N'ThanhVien');

    IF NOT EXISTS (SELECT 1 FROM THANHVIENNHOM WHERE MANHOM = @NH_QA AND MANHANVIEN = @NV03)
        INSERT INTO THANHVIENNHOM (MANHOM, MANHANVIEN, NGAYGIANHAP, VAITROTRONGNHOM)
        VALUES (@NH_QA, @NV03, DATEADD(DAY, -90, @Now), N'TruongNhom');

    IF NOT EXISTS (SELECT 1 FROM THANHVIENNHOM WHERE MANHOM = @NH_QA AND MANHANVIEN = @NV04)
        INSERT INTO THANHVIENNHOM (MANHOM, MANHANVIEN, NGAYGIANHAP, VAITROTRONGNHOM)
        VALUES (@NH_QA, @NV04, DATEADD(DAY, -80, @Now), N'ThanhVien');

    -- 5) Danh muc KPI + Ket qua KPI
    IF NOT EXISTS (SELECT 1 FROM DANHMUCKPI WHERE MADOANHMUC = 901)
        INSERT INTO DANHMUCKPI (MADOANHMUC, TENDOANHMUC, TRONGSO) VALUES (901, N'MauAI-TienDo', 0.4);
    IF NOT EXISTS (SELECT 1 FROM DANHMUCKPI WHERE MADOANHMUC = 902)
        INSERT INTO DANHMUCKPI (MADOANHMUC, TENDOANHMUC, TRONGSO) VALUES (902, N'MauAI-ChatLuong', 0.35);
    IF NOT EXISTS (SELECT 1 FROM DANHMUCKPI WHERE MADOANHMUC = 903)
        INSERT INTO DANHMUCKPI (MADOANHMUC, TENDOANHMUC, TRONGSO) VALUES (903, N'MauAI-HopTac', 0.25);

    DECLARE @KpiRows TABLE
    (
        MANHANVIEN INT,
        MADOANHMUC INT,
        DIEMSO FLOAT,
        THANG INT,
        NAM INT
    );

    INSERT INTO @KpiRows (MANHANVIEN, MADOANHMUC, DIEMSO, THANG, NAM)
    VALUES
        (@NV_TPKT, 901, 90, MONTH(@Now), YEAR(@Now)),
        (@NV_TPKT, 902, 88, MONTH(@Now), YEAR(@Now)),
        (@NV_TNBE, 901, 82, MONTH(@Now), YEAR(@Now)),
        (@NV_TNBE, 902, 80, MONTH(@Now), YEAR(@Now)),
        (@NV_TNMO, 901, 79, MONTH(@Now), YEAR(@Now)),
        (@NV_TNMO, 902, 77, MONTH(@Now), YEAR(@Now)),
        (@NV01, 901, 76, MONTH(@Now), YEAR(@Now)),
        (@NV01, 903, 73, MONTH(@Now), YEAR(@Now)),
        (@NV02, 901, 70, MONTH(@Now), YEAR(@Now)),
        (@NV02, 903, 68, MONTH(@Now), YEAR(@Now)),
        (@NV03, 901, 67, MONTH(@Now), YEAR(@Now)),
        (@NV03, 903, 66, MONTH(@Now), YEAR(@Now)),
        (@NV04, 901, 58, MONTH(@Now), YEAR(@Now)),
        (@NV04, 903, 56, MONTH(@Now), YEAR(@Now)),
        (@NV05, 901, 52, MONTH(@Now), YEAR(@Now)),
        (@NV06, 901, 48, MONTH(@Now), YEAR(@Now));

    DECLARE @NextMaKetQua INT = ISNULL((SELECT MAX(MAKETQUA) FROM KETQUAKPI), 0) + 1;

    ;WITH NeedInsert AS
    (
        SELECT kr.MANHANVIEN, kr.MADOANHMUC, kr.DIEMSO, kr.THANG, kr.NAM,
               ROW_NUMBER() OVER (ORDER BY kr.MANHANVIEN, kr.MADOANHMUC, kr.THANG, kr.NAM) AS rn
        FROM @KpiRows kr
        WHERE NOT EXISTS
        (
            SELECT 1
            FROM KETQUAKPI k
            WHERE k.MANHANVIEN = kr.MANHANVIEN
              AND k.MADOANHMUC = kr.MADOANHMUC
              AND k.THANG = kr.THANG
              AND k.NAM = kr.NAM
        )
    )
    INSERT INTO KETQUAKPI (MAKETQUA, MANHANVIEN, MADOANHMUC, DIEMSO, THANG, NAM)
    SELECT @NextMaKetQua + rn - 1, MANHANVIEN, MADOANHMUC, DIEMSO, THANG, NAM
    FROM NeedInsert;

    -- 6) Du an mau cho Project AI (>=5 du an va co ca tre/khong tre)
    IF NOT EXISTS (SELECT 1 FROM DUAN WHERE TENDUAN = N'MauAI-Project-OnTrack-1')
        INSERT INTO DUAN (TENDUAN, MOTA, NGAYBATDAU, NGAYKETTHUC, TRANGTHAI)
        VALUES (N'MauAI-Project-OnTrack-1', N'Du an mau tien do tot', DATEADD(DAY, -90, @Now), DATEADD(DAY, 60, @Now), 2);

    IF NOT EXISTS (SELECT 1 FROM DUAN WHERE TENDUAN = N'MauAI-Project-OnTrack-2')
        INSERT INTO DUAN (TENDUAN, MOTA, NGAYBATDAU, NGAYKETTHUC, TRANGTHAI)
        VALUES (N'MauAI-Project-OnTrack-2', N'Du an mau tien do tot', DATEADD(DAY, -80, @Now), DATEADD(DAY, 70, @Now), 2);

    IF NOT EXISTS (SELECT 1 FROM DUAN WHERE TENDUAN = N'MauAI-Project-Risk-1')
        INSERT INTO DUAN (TENDUAN, MOTA, NGAYBATDAU, NGAYKETTHUC, TRANGTHAI)
        VALUES (N'MauAI-Project-Risk-1', N'Du an mau nguy co tre', DATEADD(DAY, -120, @Now), DATEADD(DAY, 20, @Now), 2);

    IF NOT EXISTS (SELECT 1 FROM DUAN WHERE TENDUAN = N'MauAI-Project-Risk-2')
        INSERT INTO DUAN (TENDUAN, MOTA, NGAYBATDAU, NGAYKETTHUC, TRANGTHAI)
        VALUES (N'MauAI-Project-Risk-2', N'Du an mau nguy co tre', DATEADD(DAY, -140, @Now), DATEADD(DAY, 10, @Now), 2);

    IF NOT EXISTS (SELECT 1 FROM DUAN WHERE TENDUAN = N'MauAI-Project-Mixed-1')
        INSERT INTO DUAN (TENDUAN, MOTA, NGAYBATDAU, NGAYKETTHUC, TRANGTHAI)
        VALUES (N'MauAI-Project-Mixed-1', N'Du an mau trang thai hon hop', DATEADD(DAY, -100, @Now), DATEADD(DAY, 40, @Now), 2);

    IF NOT EXISTS (SELECT 1 FROM DUAN WHERE TENDUAN = N'MauAI-Project-Mixed-2')
        INSERT INTO DUAN (TENDUAN, MOTA, NGAYBATDAU, NGAYKETTHUC, TRANGTHAI)
        VALUES (N'MauAI-Project-Mixed-2', N'Du an mau trang thai hon hop', DATEADD(DAY, -60, @Now), DATEADD(DAY, 80, @Now), 1);

    DECLARE @DA1 INT = (SELECT TOP 1 MADUAN FROM DUAN WHERE TENDUAN = N'MauAI-Project-OnTrack-1');
    DECLARE @DA2 INT = (SELECT TOP 1 MADUAN FROM DUAN WHERE TENDUAN = N'MauAI-Project-OnTrack-2');
    DECLARE @DA3 INT = (SELECT TOP 1 MADUAN FROM DUAN WHERE TENDUAN = N'MauAI-Project-Risk-1');
    DECLARE @DA4 INT = (SELECT TOP 1 MADUAN FROM DUAN WHERE TENDUAN = N'MauAI-Project-Risk-2');
    DECLARE @DA5 INT = (SELECT TOP 1 MADUAN FROM DUAN WHERE TENDUAN = N'MauAI-Project-Mixed-1');
    DECLARE @DA6 INT = (SELECT TOP 1 MADUAN FROM DUAN WHERE TENDUAN = N'MauAI-Project-Mixed-2');

    -- 7) Cong viec mau (24 task)
    IF NOT EXISTS (SELECT 1 FROM CONGVIEC WHERE TENCONGVIEC = N'MauAI-DA1-Task-01')
        INSERT INTO CONGVIEC (MADUAN, MATRANGTHAI, TENCONGVIEC, MOTA, HANHOANTHANH, TRANGTHAI, DOUUTIEN, DOKHO, DIEMCONGVIEC, TONGCONGVIECCON, MACONGVIECCHA)
        VALUES (@DA1, @TT_HoanThanh, N'MauAI-DA1-Task-01', N'OnTrack complete', DATEADD(DAY, -5, @Now), @TT_HoanThanh, 3, 2, 80, 0, NULL);
    IF NOT EXISTS (SELECT 1 FROM CONGVIEC WHERE TENCONGVIEC = N'MauAI-DA1-Task-02')
        INSERT INTO CONGVIEC VALUES (@DA1, @TT_HoanThanh, NULL, N'MauAI-DA1-Task-02', N'OnTrack complete', DATEADD(DAY, -2, @Now), @TT_HoanThanh, 2, 2, 75, 0, NULL);
    IF NOT EXISTS (SELECT 1 FROM CONGVIEC WHERE TENCONGVIEC = N'MauAI-DA1-Task-03')
        INSERT INTO CONGVIEC VALUES (@DA1, @TT_DangLam, NULL, N'MauAI-DA1-Task-03', N'OnTrack in progress', DATEADD(DAY, 10, @Now), @TT_DangLam, 3, 3, 70, 0, NULL);
    IF NOT EXISTS (SELECT 1 FROM CONGVIEC WHERE TENCONGVIEC = N'MauAI-DA1-Task-04')
        INSERT INTO CONGVIEC VALUES (@DA1, @TT_HoanThanh, NULL, N'MauAI-DA1-Task-04', N'OnTrack complete', DATEADD(DAY, 20, @Now), @TT_HoanThanh, 1, 1, 85, 0, NULL);

    IF NOT EXISTS (SELECT 1 FROM CONGVIEC WHERE TENCONGVIEC = N'MauAI-DA2-Task-01')
        INSERT INTO CONGVIEC VALUES (@DA2, @TT_HoanThanh, NULL, N'MauAI-DA2-Task-01', N'OnTrack complete', DATEADD(DAY, -4, @Now), @TT_HoanThanh, 2, 2, 82, 0, NULL);
    IF NOT EXISTS (SELECT 1 FROM CONGVIEC WHERE TENCONGVIEC = N'MauAI-DA2-Task-02')
        INSERT INTO CONGVIEC VALUES (@DA2, @TT_HoanThanh, NULL, N'MauAI-DA2-Task-02', N'OnTrack complete', DATEADD(DAY, 3, @Now), @TT_HoanThanh, 3, 3, 78, 0, NULL);
    IF NOT EXISTS (SELECT 1 FROM CONGVIEC WHERE TENCONGVIEC = N'MauAI-DA2-Task-03')
        INSERT INTO CONGVIEC VALUES (@DA2, @TT_DangLam, NULL, N'MauAI-DA2-Task-03', N'OnTrack in progress', DATEADD(DAY, 12, @Now), @TT_DangLam, 2, 2, 73, 0, NULL);
    IF NOT EXISTS (SELECT 1 FROM CONGVIEC WHERE TENCONGVIEC = N'MauAI-DA2-Task-04')
        INSERT INTO CONGVIEC VALUES (@DA2, @TT_HoanThanh, NULL, N'MauAI-DA2-Task-04', N'OnTrack complete', DATEADD(DAY, 25, @Now), @TT_HoanThanh, 1, 1, 88, 0, NULL);

    IF NOT EXISTS (SELECT 1 FROM CONGVIEC WHERE TENCONGVIEC = N'MauAI-DA3-Task-01')
        INSERT INTO CONGVIEC VALUES (@DA3, @TT_DangLam, NULL, N'MauAI-DA3-Task-01', N'Risk overdue', DATEADD(DAY, -15, @Now), @TT_DangLam, 4, 4, 52, 0, NULL);
    IF NOT EXISTS (SELECT 1 FROM CONGVIEC WHERE TENCONGVIEC = N'MauAI-DA3-Task-02')
        INSERT INTO CONGVIEC VALUES (@DA3, @TT_DangLam, NULL, N'MauAI-DA3-Task-02', N'Risk overdue', DATEADD(DAY, -10, @Now), @TT_DangLam, 5, 4, 48, 0, NULL);
    IF NOT EXISTS (SELECT 1 FROM CONGVIEC WHERE TENCONGVIEC = N'MauAI-DA3-Task-03')
        INSERT INTO CONGVIEC VALUES (@DA3, @TT_ChoDuyet, NULL, N'MauAI-DA3-Task-03', N'Risk waiting review', DATEADD(DAY, -6, @Now), @TT_ChoDuyet, 4, 3, 55, 0, NULL);
    IF NOT EXISTS (SELECT 1 FROM CONGVIEC WHERE TENCONGVIEC = N'MauAI-DA3-Task-04')
        INSERT INTO CONGVIEC VALUES (@DA3, @TT_HoanThanh, NULL, N'MauAI-DA3-Task-04', N'Risk complete', DATEADD(DAY, -3, @Now), @TT_HoanThanh, 3, 3, 62, 0, NULL);

    IF NOT EXISTS (SELECT 1 FROM CONGVIEC WHERE TENCONGVIEC = N'MauAI-DA4-Task-01')
        INSERT INTO CONGVIEC VALUES (@DA4, @TT_DangLam, NULL, N'MauAI-DA4-Task-01', N'Risk overdue', DATEADD(DAY, -20, @Now), @TT_DangLam, 5, 5, 45, 0, NULL);
    IF NOT EXISTS (SELECT 1 FROM CONGVIEC WHERE TENCONGVIEC = N'MauAI-DA4-Task-02')
        INSERT INTO CONGVIEC VALUES (@DA4, @TT_ChuaBatDau, NULL, N'MauAI-DA4-Task-02', N'Risk not started overdue', DATEADD(DAY, -12, @Now), @TT_ChuaBatDau, 5, 4, 40, 0, NULL);
    IF NOT EXISTS (SELECT 1 FROM CONGVIEC WHERE TENCONGVIEC = N'MauAI-DA4-Task-03')
        INSERT INTO CONGVIEC VALUES (@DA4, @TT_DangLam, NULL, N'MauAI-DA4-Task-03', N'Risk overdue', DATEADD(DAY, -8, @Now), @TT_DangLam, 4, 4, 46, 0, NULL);
    IF NOT EXISTS (SELECT 1 FROM CONGVIEC WHERE TENCONGVIEC = N'MauAI-DA4-Task-04')
        INSERT INTO CONGVIEC VALUES (@DA4, @TT_HoanThanh, NULL, N'MauAI-DA4-Task-04', N'Risk complete', DATEADD(DAY, -4, @Now), @TT_HoanThanh, 3, 3, 60, 0, NULL);

    IF NOT EXISTS (SELECT 1 FROM CONGVIEC WHERE TENCONGVIEC = N'MauAI-DA5-Task-01')
        INSERT INTO CONGVIEC VALUES (@DA5, @TT_HoanThanh, NULL, N'MauAI-DA5-Task-01', N'Mixed complete', DATEADD(DAY, -2, @Now), @TT_HoanThanh, 3, 3, 72, 0, NULL);
    IF NOT EXISTS (SELECT 1 FROM CONGVIEC WHERE TENCONGVIEC = N'MauAI-DA5-Task-02')
        INSERT INTO CONGVIEC VALUES (@DA5, @TT_DangLam, NULL, N'MauAI-DA5-Task-02', N'Mixed in progress overdue', DATEADD(DAY, -1, @Now), @TT_DangLam, 4, 3, 65, 0, NULL);
    IF NOT EXISTS (SELECT 1 FROM CONGVIEC WHERE TENCONGVIEC = N'MauAI-DA5-Task-03')
        INSERT INTO CONGVIEC VALUES (@DA5, @TT_HoanThanh, NULL, N'MauAI-DA5-Task-03', N'Mixed complete', DATEADD(DAY, 6, @Now), @TT_HoanThanh, 2, 2, 77, 0, NULL);
    IF NOT EXISTS (SELECT 1 FROM CONGVIEC WHERE TENCONGVIEC = N'MauAI-DA5-Task-04')
        INSERT INTO CONGVIEC VALUES (@DA5, @TT_DangLam, NULL, N'MauAI-DA5-Task-04', N'Mixed in progress', DATEADD(DAY, 12, @Now), @TT_DangLam, 2, 2, 70, 0, NULL);

    IF NOT EXISTS (SELECT 1 FROM CONGVIEC WHERE TENCONGVIEC = N'MauAI-DA6-Task-01')
        INSERT INTO CONGVIEC VALUES (@DA6, @TT_HoanThanh, NULL, N'MauAI-DA6-Task-01', N'Mixed complete', DATEADD(DAY, -1, @Now), @TT_HoanThanh, 2, 2, 79, 0, NULL);
    IF NOT EXISTS (SELECT 1 FROM CONGVIEC WHERE TENCONGVIEC = N'MauAI-DA6-Task-02')
        INSERT INTO CONGVIEC VALUES (@DA6, @TT_HoanThanh, NULL, N'MauAI-DA6-Task-02', N'Mixed complete', DATEADD(DAY, 5, @Now), @TT_HoanThanh, 2, 2, 81, 0, NULL);
    IF NOT EXISTS (SELECT 1 FROM CONGVIEC WHERE TENCONGVIEC = N'MauAI-DA6-Task-03')
        INSERT INTO CONGVIEC VALUES (@DA6, @TT_DangLam, NULL, N'MauAI-DA6-Task-03', N'Mixed in progress', DATEADD(DAY, 14, @Now), @TT_DangLam, 3, 3, 74, 0, NULL);
    IF NOT EXISTS (SELECT 1 FROM CONGVIEC WHERE TENCONGVIEC = N'MauAI-DA6-Task-04')
        INSERT INTO CONGVIEC VALUES (@DA6, @TT_ChuaBatDau, NULL, N'MauAI-DA6-Task-04', N'Mixed not started', DATEADD(DAY, 18, @Now), @TT_ChuaBatDau, 1, 1, 69, 0, NULL);

    -- 8) Phan cong cong viec (unique theo MACONGVIEC + MANHANVIEN)
    DECLARE @TaskMap TABLE (TaskName NVARCHAR(300), MaNhanVien INT, MaNhom INT, MaPhongBan INT, LateFlag BIT);

    INSERT INTO @TaskMap (TaskName, MaNhanVien, MaNhom, MaPhongBan, LateFlag)
    VALUES
        (N'MauAI-DA1-Task-01', @NV_TNBE, @NH_BACKEND, @PB_KT, 0),
        (N'MauAI-DA1-Task-02', @NV01,    @NH_BACKEND, @PB_KT, 0),
        (N'MauAI-DA1-Task-03', @NV02,    @NH_MOBILE,  @PB_SP, 0),
        (N'MauAI-DA1-Task-04', @NV03,    @NH_QA,      @PB_SP, 0),

        (N'MauAI-DA2-Task-01', @NV_TNMO, @NH_MOBILE,  @PB_KT, 0),
        (N'MauAI-DA2-Task-02', @NV02,    @NH_MOBILE,  @PB_SP, 0),
        (N'MauAI-DA2-Task-03', @NV04,    @NH_QA,      @PB_VH, 0),
        (N'MauAI-DA2-Task-04', @NV01,    @NH_BACKEND, @PB_KT, 0),

        (N'MauAI-DA3-Task-01', @NV04,    @NH_QA,      @PB_VH, 1),
        (N'MauAI-DA3-Task-02', @NV05,    NULL,        @PB_VH, 1),
        (N'MauAI-DA3-Task-03', @NV06,    NULL,        @PB_VH, 1),
        (N'MauAI-DA3-Task-04', @NV03,    @NH_QA,      @PB_SP, 0),

        (N'MauAI-DA4-Task-01', @NV05,    NULL,        @PB_VH, 1),
        (N'MauAI-DA4-Task-02', @NV06,    NULL,        @PB_VH, 1),
        (N'MauAI-DA4-Task-03', @NV04,    @NH_QA,      @PB_VH, 1),
        (N'MauAI-DA4-Task-04', @NV_TNBE, @NH_BACKEND, @PB_KT, 0),

        (N'MauAI-DA5-Task-01', @NV01,    @NH_BACKEND, @PB_KT, 0),
        (N'MauAI-DA5-Task-02', @NV05,    NULL,        @PB_VH, 1),
        (N'MauAI-DA5-Task-03', @NV02,    @NH_MOBILE,  @PB_SP, 0),
        (N'MauAI-DA5-Task-04', @NV03,    @NH_QA,      @PB_SP, 0),

        (N'MauAI-DA6-Task-01', @NV_TNMO, @NH_MOBILE,  @PB_KT, 0),
        (N'MauAI-DA6-Task-02', @NV02,    @NH_MOBILE,  @PB_SP, 0),
        (N'MauAI-DA6-Task-03', @NV04,    @NH_QA,      @PB_VH, 0),
        (N'MauAI-DA6-Task-04', @NV06,    NULL,        @PB_VH, 0);

    INSERT INTO PHANCONGCONGVIEC
    (
        MACONGVIEC,
        MAPHONGBAN,
        MANHOM,
        MANHANVIEN,
        LOAIDOITUONG,
        NGAYGIAO,
        NGAYBATDAUDUKIEN,
        NGAYKETTHUCDUKIEN,
        NGAYBATDAUTHUCTE,
        NGAYKETTHUCTHUCTE
    )
    SELECT
        c.MACONGVIEC,
        tm.MaPhongBan,
        tm.MaNhom,
        tm.MaNhanVien,
        N'NhanVien',
        DATEADD(DAY, -30, @Now),
        DATEADD(DAY, -25, @Now),
        DATEADD(DAY, -5, @Now),
        DATEADD(DAY, -24, @Now),
        CASE WHEN tm.LateFlag = 1 THEN DATEADD(DAY, 3, @Now) ELSE DATEADD(DAY, -7, @Now) END
    FROM @TaskMap tm
    JOIN CONGVIEC c ON c.TENCONGVIEC = tm.TaskName
    WHERE NOT EXISTS
    (
        SELECT 1
        FROM PHANCONGCONGVIEC p
        WHERE p.MACONGVIEC = c.MACONGVIEC
          AND p.MANHANVIEN = tm.MaNhanVien
    );

    -- 9) Nhat ky cong viec mau
    INSERT INTO NHATKYCONGVIEC (MACONGVIEC, PHANTRAMHOANTHANH, GHICHU, NGAYCAPNHAT)
    SELECT c.MACONGVIEC,
           CASE
               WHEN c.MATRANGTHAI = @TT_HoanThanh THEN 100
               WHEN c.MATRANGTHAI = @TT_ChoDuyet THEN 90
               WHEN c.MATRANGTHAI = @TT_DangLam THEN 60
               ELSE 20
           END,
           N'Mau nhat ky cap nhat tu script seed',
           DATEADD(DAY, -1, @Now)
    FROM CONGVIEC c
    WHERE c.TENCONGVIEC LIKE N'MauAI-%'
      AND NOT EXISTS
      (
          SELECT 1
          FROM NHATKYCONGVIEC n
          WHERE n.MACONGVIEC = c.MACONGVIEC
      );

    -- 10) Du doan AI mau (de test man hinh DUDOANAI ngay)
    INSERT INTO DUDOANAI (MANHANVIEN, THANG, NAM, DIEMDUDOAN, DEXUATCAITHIEN, THOIGIANDUDOAN, MADOITUONG, XACSUATTREHAN, GIOIYNGUONLUC)
    SELECT @NV01, MONTH(@Now), YEAR(@Now), 76.5,
           N'Can duy tri tien do hien tai, tang review code',
           @Now,
           @DA1,
           0.24,
           N'On dinh, co the giao them 1-2 task do kho vua'
    WHERE NOT EXISTS
    (
        SELECT 1 FROM DUDOANAI
        WHERE MANHANVIEN = @NV01 AND THANG = MONTH(@Now) AND NAM = YEAR(@Now)
    );

    COMMIT TRAN;

    PRINT N'Seed mau thanh cong. Da giu nguyen NHANVIEN #1 va TRANGTHAICONGVIEC.';
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0
        ROLLBACK TRAN;

    DECLARE @Err NVARCHAR(4000) = ERROR_MESSAGE();
    DECLARE @ErrLine INT = ERROR_LINE();

    RAISERROR(N'Seed mau that bai tai dong %d: %s', 16, 1, @ErrLine, @Err);
END CATCH;
GO
